# Generated by Django 2.2.3 on 2016-02-11 21:27

from django.db import migrations, models
import django.db.models.deletion
import tree.models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('featured', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active_html', models.BooleanField(blank=True, default=False, null=True)),
                ('data_slide_html', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=tree.models.upload_image_path)),
                ('alt_carousel', models.CharField(blank=True, max_length=120, null=True)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Tree')),
            ],
        ),
    ]
