# Generated by Django 2.2.3 on 2020-02-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treeimage',
            name='active_html',
        ),
        migrations.RemoveField(
            model_name='treeimage',
            name='alt_carousel',
        ),
        migrations.RemoveField(
            model_name='treeimage',
            name='data_slide_html',
        ),
    ]
