# Generated by Django 2.2.3 on 2020-02-12 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_auto_20200212_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treeimage',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='treeimage',
            name='tree',
        ),
        migrations.AddField(
            model_name='treeimage',
            name='tree_obj',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='tree.Tree'),
            preserve_default=False,
        ),
    ]
