# Generated by Django 2.2.3 on 2020-02-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_treeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
