# Generated by Django 2.2.3 on 2020-02-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_tree_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
