# Generated by Django 2.2.3 on 2020-02-12 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_auto_20200212_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treeimage',
            name='title',
        ),
    ]
